/* tslint:disable */
/* eslint-disable */
/**
 * All Groups
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Fast.Admin.Service.System.SysConfig.Dto.AddSysConfigInput 添加系统配置输入
 *
 * @export
 * @interface AddSysConfigInput
 */
export interface AddSysConfigInput {

    /**
     * 编码
     *
     * @type {string}
     * @memberof AddSysConfigInput
     */
    code?: string | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof AddSysConfigInput
     */
    name?: string | null;

    /**
     * 值
     *
     * @type {string}
     * @memberof AddSysConfigInput
     */
    value?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof AddSysConfigInput
     */
    description?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AddSysConfigInput
     */
    remark?: string | null;
}
