/* tslint:disable */
/* eslint-disable */
/**
 * All Groups
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Fast.Admin.Service.System.SysConfig.Dto.UpdateSysConfigInput 更新系统配置输入
 *
 * @export
 * @interface UpdateSysConfigInput
 */
export interface UpdateSysConfigInput {

    /**
     * Id
     *
     * @type {number}
     * @memberof UpdateSysConfigInput
     */
    id?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof UpdateSysConfigInput
     */
    name?: string | null;

    /**
     * 值
     *
     * @type {string}
     * @memberof UpdateSysConfigInput
     */
    value?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof UpdateSysConfigInput
     */
    description?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateSysConfigInput
     */
    remark?: string | null;
}
