/*
 * Author 1.8K仔
 * Fast.Core 常用Using引用
 * 此文件为了减少代码，将所有的Using引用，全部放在此处
 */

global using System.Text;
global using System.Web;
global using System.Reflection;
global using System.ComponentModel;
global using System.Security.Cryptography;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Linq.Expressions;
global using System.Linq.Dynamic.Core;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Furion;
global using Furion.ConfigurableOptions;
global using Furion.DependencyInjection;
global using Furion.FriendlyException;
global using Furion.DynamicApiController;
global using static Furion.App;
global using SqlSugar;
global using Yitter.IdGenerator;
global using Fast.Iaas;
global using Fast.Iaas.AttributeFilter;
global using HttpGetAttribute = Fast.Iaas.AttributeFilter.Http.HttpGetAttribute;
global using HttpPostAttribute = Fast.Iaas.AttributeFilter.Http.HttpPostAttribute;
global using HttpPutAttribute = Fast.Iaas.AttributeFilter.Http.HttpPutAttribute;
global using HttpDeleteAttribute = Fast.Iaas.AttributeFilter.Http.HttpDeleteAttribute;
global using Fast.Iaas.EventSubscriber;
global using Fast.Iaas.Util;
global using Fast.Iaas.Util.Captcha;
global using Fast.Iaas.Util.Captcha.ClickWord;
global using Fast.Iaas.Util.Http;
global using Fast.Iaas.Util.Json.Extension;
global using Fast.Iaas.Util.Json.JsonConverter;
global using Fast.Iaas.Extension;
global using Fast.Cache.Cache;
global using Fast.Excel.AttributeFilter;
global using Fast.Excel.Extension;
global using Fast.RequestLimit.AttributeFilter;
global using Fast.RequestLimit.Filter;
global using Fast.RequestLimit.Internal;
global using Fast.Restful.Extension;
global using Fast.Restful.Internal;
global using Fast.SqlSugar.AttributeFilter;
global using Fast.SqlSugar.BaseModel;
global using Fast.SqlSugar.BaseModel.Dto;
global using Fast.SqlSugar.BaseModel.Interface;
global using Fast.SqlSugar.Const;
global using Fast.SqlSugar.Dto;
global using Fast.SqlSugar.Enum;
global using Fast.SqlSugar.Extension;
global using Fast.SqlSugar.Filter;
global using Fast.SqlSugar.Helper;
global using Fast.SqlSugar.Model;
global using Fast.SqlSugar.Repository;
global using Mapster;
global using Fast.Core;
global using Fast.Core.AdminFactory.EnumFactory;
global using Fast.Core.AdminFactory.ModelFactory;
global using Fast.Core.AdminFactory.ModelFactory.Basis;
global using Fast.Core.AdminFactory.ModelFactory.Sys;
global using Fast.Core.AdminFactory.ModelFactory.Tenant;
global using Fast.Core.AdminFactory.ServiceFactory.Tenant;
global using Fast.Core.AttributeFilter;
global using Fast.Core.Const;
global using Fast.Core.Options;